create table species
(
    species_id    int auto_increment
        primary key,
    species_name  varchar(255) null,
    lifespan      float        null,
    protect_level int          null,
    habit         varchar(255) null,
    habitat       varchar(255) null
);

INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (1, 'Panthera leo', 13, 1, 'Lions spend much of their time resting; they are inactive for about twenty hours per day.[83] Although lions can be active at any time, their activity generally peaks after dusk with a period of socialising, grooming and defecating. Intermittent bursts of', ' grasslands and savannas');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (2, 'Gorilla gorilla', 35, 2, 'Western gorillas live in groups that vary in size from two to twenty individuals. Such groups are composed of at least one male, several females and their offspring', 'forests');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (3, 'Bradypus tridactylus', 6, 5, 'Pale-throated sloths are solitary,[8] herbivorous animals that spend almost their entire lives in trees. Depending on habitat, population densities of anything from 1.7 to 221 per square kilometre (4.4 to 572.4/sq mi) have been reported.[2]', ' tropical forests of northern South America');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (4, 'Loxodonta africana', 70, 1, 'The core of elephant society is the family unit, which comprises several adult cows, their daughters, and their prepubertal sons. Iain Douglas-Hamilton, who observed African bush elephants for 4.5 years in Lake Manyara National Park, coined the term ''kins', 'subtropical and temperate forests, dry and seasonally flooded grasslands and woodlands, wetlands and agricultural land from sea level to mountain slopes. In Mali and Namibia, it also inhabits desert areas.');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (5, 'Giraffa camelopardalis', 24, 2, 'The giraffe''s chief distinguishing characteristics are its extremely long neck and legs, its horn-like ossicones, and its distinctive coat patterns. It is classified under the family Giraffidae, along with its closest extant relative, the okapi. ', ' in the north to South Africa in the south, and from Niger in the west to Somalia in the east.');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (6, 'Ailuropoda melanoleuca', 25, 1, 'The giant panda lives in a few mountain ranges in central China, mainly in Sichuan, but also in neighbouring Shaanxi and Gansu.[10] As a result of farming, deforestation, and other development, the giant panda has been driven out of the lowland areas wher', 'South Central China');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (7, 'Crocodylus porosus', 75, 3, 'a large and opportunistic hypercarnivorous apex predator. It ambushes most of its prey and then drowns or swallows it whole. It is capable of prevailing over almost any animal that enters its territory', 'India''s east coast across Southeast Asia and the Sundaic region to northern Australia and Micronesia');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (8, 'Struthio camelus', 30, 2, 'The common ostrich''s diet consists mainly of plant matter, though it also eats invertebrates and small reptiles. It lives in nomadic groups of 5 to 50 birds. When threatened, the ostrich will either hide itself by lying flat against the ground, or run awa', ' certain large areas of Africa');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (9, 'Zalophus californianus', 20, 2, 'California sea lions have a polygynous breeding pattern. From May to August, males establish territories and try to attract females with which to mate. Females are free to move in between territories, and are not coerced by males', ' western North America');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (10, 'Myrmecophaga tridactyla', 23, 2, 'Even for an anteater, the neck is especially thick compared to the back of the head,[18] and a small hump is found at the back of the neck. The coat is mostly greyish, brown or black and salted with white.', ' Central and South America.');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (11, 'Camelus dromedarius', 40, 1, 'The species'' distinctive features include its long, curved neck, narrow chest, a single hump (compared with two on the Bactrian camel and wild Bactrian camel), and long hairs on the throat, shoulders and hump', 'semi-arid to arid regions ');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (12, 'Conraua goliath', 5, 5, ' This species has a relatively small habitat range in Cameroon and Equatorial Guinea.[3] Its numbers are dwindling due to habitat destruction and its collection for food and the pet trade', 'water');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (13, 'Phoenicopterus ruber', 30, 4, ' a large wading bird with reddish-pink plumage. Like all flamingos, it lays a single chalky-white egg on a mud mound, between May and August; incubation until hatching takes from 28 to 32 days; both parents brood the young for a period up to 6 years when ', ' North America.');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (14, 'Acinonyx jubatus', 15, 1, 'The cheetah is a lightly built, spotted cat characterised by a small rounded head, a short snout, black tear-like facial streaks, a deep chest, long thin legs and a long tail. Its slender, canine-like form is highly adapted for speed, and contrasts sharpl', ' Serengeti, arid mountain ranges in the Sahara and hilly desert terrain ');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (15, 'Acipenser fulvescens', 80, 5, 'Its diet consists of insect larvae, worms (including leeches), and other small organisms (primarily metazoan) it finds in the mud. Fish are rarely found in its diet and are likely incidental items only, with the possible exception of the invasive round go', 'North American temperate freshwater');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (16, 'Aplysia vaccaria', 6, 5, 'hey grow very quickly, at an average rate of 4.9 grams per day.[5] This high rate of growth makes sense given that Aplysia vaccaria is the largest known species of sea slug.[6] Aplysia vaccaria is a herbivore which feeds on brown algae, which is notable g', ' northeast Pacific Ocean off California, United States and Baja California, Mexico, including the Gulf of California');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (17, 'Phyllorhiza punctata', 0.75, 1, 'True jellyfish go through a two-stage life cycle which consists of a medusa stage (adult) and a polyp stage (juvenile). In the medusa stage male jellyfish release sperm into the water column and the female jellyfish gathers the sperm into her mouth where ', ' Australia to Japan');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (18, 'Diceros bicornis', 50, 2, 'Black rhinoceros are generally thought to be solitary, with the only strong bond between a mother and her calf. In addition, males and females have a consort relationship during mating, also subadults and young adults frequently form loose associations wi', 'eastern and southern Africa');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (19, 'Tyrannosaurus rex', 30, 5, 'Evidence also strongly suggests that tyrannosaurs were at least occasionally cannibalistic. Tyrannosaurus itself has strong evidence pointing towards it having been cannibalistic in at least a scavenging capacity based on tooth marks on the foot bones', 'western North America, on what was then an island continent known as Laramidia');
INSERT INTO user062db.species (species_id, species_name, lifespan, protect_level, habit, habitat) VALUES (20, 'Panthera tigris', 22, 1, 'Adult tigers lead largely solitary lives. They establish and maintain territories but have much wider home ranges within which they roam. Resident adults of either sex generally confine their movements to their home ranges, within which they satisfy their', 'forest');